# Generated by Django 4.2.1 on 2023-05-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMangerAPI', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
